// Generated by tools/generate_mode5_contract.py. DO NOT EDIT.
#ifndef SONIC_G1_MODE5_CONTRACT_GENERATED_HPP
#define SONIC_G1_MODE5_CONTRACT_GENERATED_HPP

#include <array>
#include <bit>
#include <cstdint>
#include <string_view>

namespace sonic::mode5_contract {
struct CheckpointArtifact {
  std::string_view path_from_deploy_root;
  std::uint64_t size;
  std::string_view sha256;
};

inline constexpr std::string_view kCapabilitySchema = "motionlcm.sonic.capabilities.v5";
inline constexpr std::string_view kProfileId = "sonic-g1-mode5-derived-v1";
inline constexpr std::string_view kCanonicalSha256 = "1ab7b04a98e5e32a15371c215291940d134e9978ad3d35c16f6a74bc964a1420";
inline constexpr std::string_view kCanonicalization = "json.dumps(sort_keys=True,separators=(\",\",\":\"),ensure_ascii=False,allow_nan=False)-utf8-sha256";
inline constexpr std::string_view kStatus = "experimental-cross-revision";
inline constexpr bool kVendorAttested = false;
inline constexpr std::string_view kCompatibilityBasis = "released-mode11-policy-semantics-on-mode5-physical-plant";
inline constexpr int kContractRevision = 3;
inline constexpr std::string_view kContractPathFromDeployRoot = "g1/sonic_g1_mode5_derived_v1.contract.json";
inline constexpr std::string_view kUnitreeModelRepository = "unitreerobotics/unitree_ros";
inline constexpr std::string_view kUnitreeModelRevision = "daadf41ee9afce8f90fdc09a98506012691fa122";
inline constexpr std::string_view kUnitreeModelSourcePath = "robots/g1_description/g1_29dof_rev_1_0.xml";
inline constexpr std::string_view kUnitreeModelSourceSha256 = "165fa7a5275745e45fa25e1bc78010c1055d81bb81c013b3c7bc8b9347a3b9c3";
inline constexpr std::string_view kUnitreeActuatorRepository = "unitreerobotics/unitree_rl_mjlab";
inline constexpr std::string_view kUnitreeActuatorRevision = "1425b15f73bd4095f0df53709d7c389c3eb9e790";
inline constexpr std::string_view kUnitreeActuatorSourcePath = "src/assets/robots/unitree_g1/g1_constants.py";
inline constexpr std::string_view kUnitreeActuatorSourceSha256 = "136b59af97082a74fd3a2a4250bc2e290b3ba6a26533b1492be52114dd844c5d";
inline constexpr std::string_view kTakeoverSourceRepository = "unitreerobotics/unitree_sdk2";
inline constexpr std::string_view kTakeoverSourceRevision = "9754cd153af3da471b0fe5f3aa535e426fb11db3";
inline constexpr std::string_view kTakeoverSourcePath = "example/g1/low_level/g1_ankle_swing_example.cpp";
inline constexpr std::string_view kTakeoverSourceSha256 = "9394824751ee4f74d252546fe4f3c20145f9148becfbb9eeb53cbeef449c6b8b";
inline constexpr std::string_view kCheckpointSource = "nvidia/GEAR-SONIC";
inline constexpr std::string_view kCheckpointRevision = "9c0ff22b4ffec27c5392e8e284eb2f2df7a5b4e2";
inline constexpr std::string_view kCheckpointBundleSha256 = "7d6dfd88dfbb2fce6b69a9b9db9e01ec918a1d93c355ba5f0f5ecb114d09df24";
inline constexpr std::array<CheckpointArtifact, 3> kCheckpointArtifacts = {{
    {"policy/release/model_decoder.onnx", std::uint64_t{40900688}, "c7241a123eaa36b5d64bad19540efde93cac1ad443bd4572fd12ca99898118ed"},
    {"policy/release/model_encoder.onnx", std::uint64_t{50100513}, "013ab0287236aa2721e13f1e936d699db982302d0de0bfcdae76d5c3245362d3"},
    {"policy/release/observation_config.yaml", std::uint64_t{2336}, "466d05947c78af6c76388adfb86e3a2a77b2a1d921a64883ed3d085ebf58de1b"},
}};
inline constexpr int kCheckpointTrainingModeMachine = 11;
inline constexpr int kPhysicalPlantModeMachine = 5;
inline constexpr std::string_view kPolicyParameterSemantics = "released-mode11-policy-values-preserved-bit-exact";
inline constexpr std::string_view kJointParameterSha256 = "8c46e85155070a359dce3059a86a98b0c7cd8d8b1ba3079e2f4d97a13236237b";
inline constexpr std::string_view kFkMjcfPathFromWbcRoot = "gear_sonic/data/assets/robot_description/mjcf/g1_29dof_rev_1_0.xml";
inline constexpr std::uint64_t kFkMjcfSize = 36030;
inline constexpr std::string_view kFkMjcfSha256 = "15a330f1dbff68cdbeb8284be6162a857bdcd21a858f65a8617fb32d5115f209";
inline constexpr std::string_view kSimMjcfPathFromWbcRoot = "decoupled_wbc/control/robot_model/model_data/g1/g1_29dof_with_hand_rev_1_0_activatedfinger.xml";
inline constexpr std::uint64_t kSimMjcfSize = 45258;
inline constexpr std::string_view kSimMjcfSha256 = "388d682c8ed36e833eca986109fdca2797c4d5f3882822e2b03a1af1a2675f07";
inline constexpr std::string_view kSimScenePathFromWbcRoot = "decoupled_wbc/control/robot_model/model_data/g1/scene_29dof_activated3dex.xml";
inline constexpr std::uint64_t kSimSceneSize = 1169;
inline constexpr std::string_view kSimSceneSha256 = "88a24971e125eb20382e59217a18ee97eb0756c3e450e29a95a9e34ef397fbfc";
inline constexpr std::string_view kSimConfigPathFromWbcRoot = "gear_sonic/utils/mujoco_sim/wbc_configs/g1_29dof_sonic_model12.yaml";
inline constexpr std::uint64_t kSimConfigSize = 12448;
inline constexpr std::string_view kSimConfigSha256 = "15520caa4b5748fab451f7f34661646bfb9db9dbd06fd8ed240f507f629d01a6";
inline constexpr std::string_view kSimSceneInclude = "g1_29dof_with_hand_rev_1_0_activatedfinger.xml";
inline constexpr std::string_view kSimConfigSceneOverride = "decoupled_wbc/control/robot_model/model_data/g1/scene_29dof_activated3dex.xml";
inline constexpr std::string_view kKinematicsSha256 = "4b4272979a730962981652897f5035d02abbab9db4197dd29320266f564ffdc5";
inline constexpr std::uint8_t kModeMachine = 5;
inline constexpr std::uint8_t kModePr = 0;
inline constexpr int kActiveMotorCount = 29;
inline constexpr int kMotorMode = 1;
inline constexpr int kWriterRateHz = 500;
inline constexpr double kPhysicsTimestepSeconds = std::bit_cast<double>(std::uint64_t{0x3f60624dd2f1a9fcull});
inline constexpr int kPhysicsRateHz = 500;
inline constexpr int kPhysicsStepsPerLowcmdPeriod = 1;
inline constexpr std::string_view kTorqueApplication = "external-pd-recomputed-once-per-mujoco-step";
inline constexpr double kMeasuredPositionTolerance = std::bit_cast<double>(std::uint64_t{0x0000000000000000ull});
inline constexpr double kMeasuredVelocityTolerance = std::bit_cast<double>(std::uint64_t{0x0000000000000000ull});
inline constexpr double kTakeoverDurationSeconds = std::bit_cast<double>(std::uint64_t{0x4008000000000000ull});
inline constexpr std::string_view kTakeoverSemantics = "fixed-duration-linear-position-ramp-and-idle-hold";
inline constexpr std::string_view kTakeoverSourceRole = "official-g1-low-level-init-and-idle-gain-schedule";
inline constexpr float kShutdownQ = 0.0f;
inline constexpr float kShutdownDq = 0.0f;
inline constexpr float kShutdownKp = 0.0f;
inline constexpr float kShutdownKd = 8.0f;
inline constexpr float kShutdownTauFf = 0.0f;
inline constexpr int kShutdownRepeatMs = 250;

inline constexpr std::array<std::string_view, 29> kJointNames = {
    "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint", "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint", "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint", "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint", "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint", "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint", "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint", "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint"
};
inline constexpr std::array<std::string_view, 29> kPhysicalActuator = {
    "7520_14", "7520_22", "7520_14", "7520_22", "5020x2", "5020x2", "7520_14", "7520_22", "7520_14", "7520_22", "5020x2", "5020x2", "7520_14", "5020x2", "5020x2", "5020", "5020", "5020", "5020", "5020", "4010", "4010", "5020", "5020", "5020", "5020", "5020", "4010", "4010"
};
inline constexpr std::array<std::string_view, 29> kPolicyGainBasis = {
    "7520_22-mode11", "7520_22", "7520_14", "7520_22", "5020x2", "5020x2", "7520_22-mode11", "7520_22", "7520_14", "7520_22", "5020x2", "5020x2", "7520_14", "5020x2", "5020x2", "5020", "5020", "5020", "5020", "5020", "4010", "4010", "5020", "5020", "5020", "5020", "5020", "4010", "4010"
};
inline constexpr std::array<std::string_view, 29> kTakeoverGainBasis = {
    "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example", "unitree-sdk2-g1-ankle-swing-example"
};
inline constexpr std::array<int, 29> kMujocoOrderInIsaaclabIndex = {
    0, 3, 6, 9, 13, 17, 1, 4, 7, 10, 14, 18, 2, 5, 8, 11, 15, 19, 21, 23, 25, 27, 12, 16, 20, 22, 24, 26, 28
};
inline constexpr std::array<int, 29> kIsaaclabOrderInMujocoIndex = {
    0, 6, 12, 1, 7, 13, 2, 8, 14, 3, 9, 15, 22, 4, 10, 16, 23, 5, 11, 17, 24, 18, 25, 19, 26, 20, 27, 21, 28
};
inline constexpr std::array<double, 29> kCommandSign = {
    std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3ff0000000000000ull})
};
inline constexpr std::array<double, 29> kCommandOffset = {
    std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull})
};
inline constexpr std::array<double, 29> kPositionLower = {
    std::bit_cast<double>(std::uint64_t{0xc0043edfa43fe5c9ull}), std::bit_cast<double>(std::uint64_t{0xbfe0c154c985f06full}), std::bit_cast<double>(std::uint64_t{0xc0060f9096bb98c8ull}), std::bit_cast<double>(std::uint64_t{0xbfb657214f0520d1ull}), std::bit_cast<double>(std::uint64_t{0xbfebece9a2c66905ull}), std::bit_cast<double>(std::uint64_t{0xbfd0c154c985f06full}), std::bit_cast<double>(std::uint64_t{0xc0043edfa43fe5c9ull}), std::bit_cast<double>(std::uint64_t{0xc007bc9eecbfb15bull}), std::bit_cast<double>(std::uint64_t{0xc0060f9096bb98c8ull}), std::bit_cast<double>(std::uint64_t{0xbfb657214f0520d1ull}), std::bit_cast<double>(std::uint64_t{0xbfebece9a2c66905ull}), std::bit_cast<double>(std::uint64_t{0xbfd0c154c985f06full}), std::bit_cast<double>(std::uint64_t{0xc004f1a9fbe76c8bull}), std::bit_cast<double>(std::uint64_t{0xbfe0a3d70a3d70a4ull}), std::bit_cast<double>(std::uint64_t{0xbfe0a3d70a3d70a4ull}), std::bit_cast<double>(std::uint64_t{0xc008b6ae7d566cf4ull}), std::bit_cast<double>(std::uint64_t{0xbff9694467381d7eull}), std::bit_cast<double>(std::uint64_t{0xc004f1a9fbe76c8bull}), std::bit_cast<double>(std::uint64_t{0xbff0c154c985f06full}), std::bit_cast<double>(std::uint64_t{0xbfff8e368f084620ull}), std::bit_cast<double>(std::uint64_t{0xbff9d4b48d3ae686ull}), std::bit_cast<double>(std::uint64_t{0xbff9d4b48d3ae686ull}), std::bit_cast<double>(std::uint64_t{0xc008b6ae7d566cf4ull}), std::bit_cast<double>(std::uint64_t{0xc00203126e978d50ull}), std::bit_cast<double>(std::uint64_t{0xc004f1a9fbe76c8bull}), std::bit_cast<double>(std::uint64_t{0xbff0c154c985f06full}), std::bit_cast<double>(std::uint64_t{0xbfff8e368f084620ull}), std::bit_cast<double>(std::uint64_t{0xbff9d4b48d3ae686ull}), std::bit_cast<double>(std::uint64_t{0xbff9d4b48d3ae686ull})
};
inline constexpr std::array<double, 29> kPositionUpper = {
    std::bit_cast<double>(std::uint64_t{0x400709d495182a99ull}), std::bit_cast<double>(std::uint64_t{0x4007bc9eecbfb15bull}), std::bit_cast<double>(std::uint64_t{0x40060f9096bb98c8ull}), std::bit_cast<double>(std::uint64_t{0x400709d495182a99ull}), std::bit_cast<double>(std::uint64_t{0x3fe0c154c985f06full}), std::bit_cast<double>(std::uint64_t{0x3fd0c154c985f06full}), std::bit_cast<double>(std::uint64_t{0x400709d495182a99ull}), std::bit_cast<double>(std::uint64_t{0x3fe0c154c985f06full}), std::bit_cast<double>(std::uint64_t{0x40060f9096bb98c8ull}), std::bit_cast<double>(std::uint64_t{0x400709d495182a99ull}), std::bit_cast<double>(std::uint64_t{0x3fe0c154c985f06full}), std::bit_cast<double>(std::uint64_t{0x3fd0c154c985f06full}), std::bit_cast<double>(std::uint64_t{0x4004f1a9fbe76c8bull}), std::bit_cast<double>(std::uint64_t{0x3fe0a3d70a3d70a4ull}), std::bit_cast<double>(std::uint64_t{0x3fe0a3d70a3d70a4ull}), std::bit_cast<double>(std::uint64_t{0x40055cfaacd9e83eull}), std::bit_cast<double>(std::uint64_t{0x400203126e978d50ull}), std::bit_cast<double>(std::uint64_t{0x4004f1a9fbe76c8bull}), std::bit_cast<double>(std::uint64_t{0x4000c154c985f06full}), std::bit_cast<double>(std::uint64_t{0x3fff8e368f084620ull}), std::bit_cast<double>(std::uint64_t{0x3ff9d4b48d3ae686ull}), std::bit_cast<double>(std::uint64_t{0x3ff9d4b48d3ae686ull}), std::bit_cast<double>(std::uint64_t{0x40055cfaacd9e83eull}), std::bit_cast<double>(std::uint64_t{0x3ff9694467381d7eull}), std::bit_cast<double>(std::uint64_t{0x4004f1a9fbe76c8bull}), std::bit_cast<double>(std::uint64_t{0x4000c154c985f06full}), std::bit_cast<double>(std::uint64_t{0x3fff8e368f084620ull}), std::bit_cast<double>(std::uint64_t{0x3ff9d4b48d3ae686ull}), std::bit_cast<double>(std::uint64_t{0x3ff9d4b48d3ae686ull})
};
inline constexpr std::array<double, 29> kPlantEffortLimit = {
    std::bit_cast<double>(std::uint64_t{0x4056000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4061600000000000ull}), std::bit_cast<double>(std::uint64_t{0x4056000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4061600000000000ull}), std::bit_cast<double>(std::uint64_t{0x4049000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4049000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4056000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4061600000000000ull}), std::bit_cast<double>(std::uint64_t{0x4056000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4061600000000000ull}), std::bit_cast<double>(std::uint64_t{0x4049000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4049000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4056000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4049000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4049000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4039000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4039000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4039000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4039000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4039000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4014000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4014000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4039000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4039000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4039000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4039000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4039000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4014000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4014000000000000ull})
};
inline constexpr std::array<double, 29> kPlantVelocityLimit = {
    std::bit_cast<double>(std::uint64_t{0x4040000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4034000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4040000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4034000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4040000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4034000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4040000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4034000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4040000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4036000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4036000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4042800000000000ull}), std::bit_cast<double>(std::uint64_t{0x4036000000000000ull}), std::bit_cast<double>(std::uint64_t{0x4036000000000000ull})
};
inline constexpr std::array<double, 29> kPlantArmature = {
    std::bit_cast<double>(std::uint64_t{0x3f84d7f39c6f61e3ull}), std::bit_cast<double>(std::uint64_t{0x3f99b451abc43e89ull}), std::bit_cast<double>(std::uint64_t{0x3f84d7f39c6f61e3ull}), std::bit_cast<double>(std::uint64_t{0x3f99b451abc43e89ull}), std::bit_cast<double>(std::uint64_t{0x3f7d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f7d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f84d7f39c6f61e3ull}), std::bit_cast<double>(std::uint64_t{0x3f99b451abc43e89ull}), std::bit_cast<double>(std::uint64_t{0x3f84d7f39c6f61e3ull}), std::bit_cast<double>(std::uint64_t{0x3f99b451abc43e89ull}), std::bit_cast<double>(std::uint64_t{0x3f7d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f7d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f84d7f39c6f61e3ull}), std::bit_cast<double>(std::uint64_t{0x3f7d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f7d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f6d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f6d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f6d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f6d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f6d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f716872b020c49cull}), std::bit_cast<double>(std::uint64_t{0x3f716872b020c49cull}), std::bit_cast<double>(std::uint64_t{0x3f6d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f6d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f6d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f6d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f6d92245a525bedull}), std::bit_cast<double>(std::uint64_t{0x3f716872b020c49cull}), std::bit_cast<double>(std::uint64_t{0x3f716872b020c49cull})
};
inline constexpr std::array<double, 29> kPassiveDamping = {
    std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fa999999999999aull})
};
inline constexpr std::array<double, 29> kPassiveFrictionLoss = {
    std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fb999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fb999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fb999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fb999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fb999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fb999999999999aull})
};
inline constexpr std::array<float, 29> kPolicyKp = {
    std::bit_cast<float>(std::uint32_t{0x42c63265u}), std::bit_cast<float>(std::uint32_t{0x42c63265u}), std::bit_cast<float>(std::uint32_t{0x4220b78au}), std::bit_cast<float>(std::uint32_t{0x42c63265u}), std::bit_cast<float>(std::uint32_t{0x41e4028du}), std::bit_cast<float>(std::uint32_t{0x41e4028du}), std::bit_cast<float>(std::uint32_t{0x42c63265u}), std::bit_cast<float>(std::uint32_t{0x42c63265u}), std::bit_cast<float>(std::uint32_t{0x4220b78au}), std::bit_cast<float>(std::uint32_t{0x42c63265u}), std::bit_cast<float>(std::uint32_t{0x41e4028du}), std::bit_cast<float>(std::uint32_t{0x41e4028du}), std::bit_cast<float>(std::uint32_t{0x4220b78au}), std::bit_cast<float>(std::uint32_t{0x41e4028du}), std::bit_cast<float>(std::uint32_t{0x41e4028du}), std::bit_cast<float>(std::uint32_t{0x4164028du}), std::bit_cast<float>(std::uint32_t{0x4164028du}), std::bit_cast<float>(std::uint32_t{0x4164028du}), std::bit_cast<float>(std::uint32_t{0x4164028du}), std::bit_cast<float>(std::uint32_t{0x4164028du}), std::bit_cast<float>(std::uint32_t{0x41863a04u}), std::bit_cast<float>(std::uint32_t{0x41863a04u}), std::bit_cast<float>(std::uint32_t{0x4164028du}), std::bit_cast<float>(std::uint32_t{0x4164028du}), std::bit_cast<float>(std::uint32_t{0x4164028du}), std::bit_cast<float>(std::uint32_t{0x4164028du}), std::bit_cast<float>(std::uint32_t{0x4164028du}), std::bit_cast<float>(std::uint32_t{0x41863a04u}), std::bit_cast<float>(std::uint32_t{0x41863a04u})
};
inline constexpr std::array<float, 29> kPolicyKd = {
    std::bit_cast<float>(std::uint32_t{0x40c9e1b4u}), std::bit_cast<float>(std::uint32_t{0x40c9e1b4u}), std::bit_cast<float>(std::uint32_t{0x4023b477u}), std::bit_cast<float>(std::uint32_t{0x40c9e1b4u}), std::bit_cast<float>(std::uint32_t{0x3fe83fc2u}), std::bit_cast<float>(std::uint32_t{0x3fe83fc2u}), std::bit_cast<float>(std::uint32_t{0x40c9e1b4u}), std::bit_cast<float>(std::uint32_t{0x40c9e1b4u}), std::bit_cast<float>(std::uint32_t{0x4023b477u}), std::bit_cast<float>(std::uint32_t{0x40c9e1b4u}), std::bit_cast<float>(std::uint32_t{0x3fe83fc2u}), std::bit_cast<float>(std::uint32_t{0x3fe83fc2u}), std::bit_cast<float>(std::uint32_t{0x4023b477u}), std::bit_cast<float>(std::uint32_t{0x3fe83fc2u}), std::bit_cast<float>(std::uint32_t{0x3fe83fc2u}), std::bit_cast<float>(std::uint32_t{0x3f683fc2u}), std::bit_cast<float>(std::uint32_t{0x3f683fc2u}), std::bit_cast<float>(std::uint32_t{0x3f683fc2u}), std::bit_cast<float>(std::uint32_t{0x3f683fc2u}), std::bit_cast<float>(std::uint32_t{0x3f683fc2u}), std::bit_cast<float>(std::uint32_t{0x3f88b8dcu}), std::bit_cast<float>(std::uint32_t{0x3f88b8dcu}), std::bit_cast<float>(std::uint32_t{0x3f683fc2u}), std::bit_cast<float>(std::uint32_t{0x3f683fc2u}), std::bit_cast<float>(std::uint32_t{0x3f683fc2u}), std::bit_cast<float>(std::uint32_t{0x3f683fc2u}), std::bit_cast<float>(std::uint32_t{0x3f683fc2u}), std::bit_cast<float>(std::uint32_t{0x3f88b8dcu}), std::bit_cast<float>(std::uint32_t{0x3f88b8dcu})
};
inline constexpr std::array<float, 29> kTakeoverKp = {
    std::bit_cast<float>(std::uint32_t{0x42700000u}), std::bit_cast<float>(std::uint32_t{0x42700000u}), std::bit_cast<float>(std::uint32_t{0x42700000u}), std::bit_cast<float>(std::uint32_t{0x42c80000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42700000u}), std::bit_cast<float>(std::uint32_t{0x42700000u}), std::bit_cast<float>(std::uint32_t{0x42700000u}), std::bit_cast<float>(std::uint32_t{0x42c80000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42700000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u}), std::bit_cast<float>(std::uint32_t{0x42200000u})
};
inline constexpr std::array<float, 29> kTakeoverKd = {
    std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x40000000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x40000000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u}), std::bit_cast<float>(std::uint32_t{0x3f800000u})
};
inline constexpr std::array<double, 29> kPolicyActionScale = {
    std::bit_cast<double>(std::uint64_t{0x3fd6713cca842003ull}), std::bit_cast<double>(std::uint64_t{0x3fd6713cca842003ull}), std::bit_cast<double>(std::uint64_t{0x3fe185802a245631ull}), std::bit_cast<double>(std::uint64_t{0x3fd6713cca842003ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fd6713cca842003ull}), std::bit_cast<double>(std::uint64_t{0x3fd6713cca842003ull}), std::bit_cast<double>(std::uint64_t{0x3fe185802a245631ull}), std::bit_cast<double>(std::uint64_t{0x3fd6713cca842003ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fe185802a245631ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fb3127d3196b9a0ull}), std::bit_cast<double>(std::uint64_t{0x3fb3127d3196b9a0ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fdc11a695046077ull}), std::bit_cast<double>(std::uint64_t{0x3fb3127d3196b9a0ull}), std::bit_cast<double>(std::uint64_t{0x3fb3127d3196b9a0ull})
};
inline constexpr std::array<double, 29> kDefaultAngles = {
    std::bit_cast<double>(std::uint64_t{0xbfd3f7ced916872bull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3fe56872b020c49cull}), std::bit_cast<double>(std::uint64_t{0xbfd73b645a1cac08ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0xbfd3f7ced916872bull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3fe56872b020c49cull}), std::bit_cast<double>(std::uint64_t{0xbfd73b645a1cac08ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3fe3333333333333ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3fc999999999999aull}), std::bit_cast<double>(std::uint64_t{0xbfc999999999999aull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x3fe3333333333333ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull}), std::bit_cast<double>(std::uint64_t{0x0000000000000000ull})
};

consteval bool JointMapIsABijection() {
  std::array<bool, 29> seen{};
  for (int hardware_index = 0; hardware_index < 29; ++hardware_index) {
    const int policy_index = kMujocoOrderInIsaaclabIndex[hardware_index];
    if (policy_index < 0 || policy_index >= 29 || seen[policy_index] ||
        kIsaaclabOrderInMujocoIndex[policy_index] != hardware_index) return false;
    seen[policy_index] = true;
  }
  return true;
}
consteval bool JointRowsAreSafe() {
  for (int index = 0; index < 29; ++index) {
    if (!(kPositionLower[index] < kPositionUpper[index]) ||
        kDefaultAngles[index] < kPositionLower[index] ||
        kDefaultAngles[index] > kPositionUpper[index] ||
        (kCommandSign[index] != -1.0 && kCommandSign[index] != 1.0) ||
        kPolicyKp[index] <= 0.0f || kPolicyKd[index] <= 0.0f ||
        kTakeoverKp[index] <= 0.0f || kTakeoverKd[index] <= 0.0f ||
        kTakeoverGainBasis[index].empty() ||
        kPolicyActionScale[index] <= 0.0 ||
        kPlantEffortLimit[index] <= 0.0 ||
        kPlantVelocityLimit[index] <= 0.0) return false;
  }
  return true;
}
consteval bool TakeoverScheduleIsPinned() {
  constexpr std::array<float, 29> expected_kp{{
      60, 60, 60, 100, 40, 40, 60, 60, 60, 100, 40, 40, 60, 40, 40,
      40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
  }};
  constexpr std::array<float, 29> expected_kd{{
      1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  }};
  return kTakeoverKp == expected_kp && kTakeoverKd == expected_kd;
}
static_assert(!kVendorAttested);
static_assert(kModeMachine == kPhysicalPlantModeMachine);
static_assert(kActiveMotorCount == 29);
static_assert(kPhysicsTimestepSeconds == 0.002);
static_assert(kPhysicsRateHz == kWriterRateHz * kPhysicsStepsPerLowcmdPeriod);
static_assert(kPhysicsTimestepSeconds * kPhysicsRateHz == 1.0);
static_assert(kPhysicsStepsPerLowcmdPeriod == 1);
static_assert(!kTorqueApplication.empty());
static_assert(kTakeoverDurationSeconds == 3.0);
static_assert(!kTakeoverSourceRepository.empty());
static_assert(!kTakeoverSourceRevision.empty());
static_assert(!kTakeoverSourcePath.empty());
static_assert(kTakeoverSourceSha256.size() == 64);
static_assert(JointMapIsABijection());
static_assert(JointRowsAreSafe());
static_assert(TakeoverScheduleIsPinned());

}  // namespace sonic::mode5_contract

#endif  // SONIC_G1_MODE5_CONTRACT_GENERATED_HPP
