#!/usr/bin/env python3
"""Generate the checked C++ FK golden with MuJoCo, independently of RobotFK.

Run this only in the pinned, network-isolated sonic-sim image documented in
README.md.  The output is a C++ data header consumed by test_fk.cpp.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path

import mujoco


EXPECTED_MUJOCO_VERSION = "3.11.0"
SOURCE_IMAGE_ID = (
    "sha256:ccbb35e993276b33d338dfd6e273a5b2f83bbba4a7e678f3bd1fb65c707325a7"
)
MODEL_RELATIVE_PATH = (
    "gear_sonic/data/assets/robot_description/mjcf/g1_29dof_rev_1_0.xml"
)
CONTRACT_RELATIVE_PATH = (
    "gear_sonic_deploy/g1/sonic_g1_mode5_derived_v1.contract.json"
)


POLICY_JOINT_FRAMES = (
    (
        0.11, -0.17, 0.23, 0.07, -0.09, 0.13, -0.19, 0.21, -0.15,
        0.31, 0.27, -0.22, 0.18, -0.16, 0.14, 0.12, -0.11, 0.08,
        -0.07, 0.20, -0.18, 0.33, 0.29, -0.24, 0.26, -0.28, 0.22,
        -0.20, 0.17,
    ),
    (
        -0.21, 0.16, -0.12, -0.18, 0.15, -0.10, 0.22, -0.20, 0.17,
        0.42, 0.36, 0.19, -0.17, 0.11, -0.13, -0.14, 0.16, -0.09,
        0.08, -0.23, 0.24, 0.47, 0.39, 0.27, -0.25, 0.31, -0.29,
        0.26, -0.22,
    ),
)
ROOT_TRANSLATIONS = ((0.13, -0.21, 0.94), (-0.27, 0.16, 1.08))
ROOT_RPY = ((0.17, -0.31, 0.43), (-0.29, 0.22, -0.37))


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rpy_to_wxyz(roll: float, pitch: float, yaw: float) -> tuple[float, ...]:
    cr, sr = math.cos(roll / 2.0), math.sin(roll / 2.0)
    cp, sp = math.cos(pitch / 2.0), math.sin(pitch / 2.0)
    cy, sy = math.cos(yaw / 2.0), math.sin(yaw / 2.0)
    return (
        cr * cp * cy + sr * sp * sy,
        sr * cp * cy - cr * sp * sy,
        cr * sp * cy + sr * cp * sy,
        cr * cp * sy - sr * sp * cy,
    )


def cpp_float(value: float) -> str:
    if value == 0.0:
        return "0.0"
    return format(float(value), ".17g")


def cpp_array(values: tuple[float, ...] | list[float]) -> str:
    return ", ".join(cpp_float(value) for value in values)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--wbc-root", type=Path, required=True)
    args = parser.parse_args()

    if mujoco.__version__ != EXPECTED_MUJOCO_VERSION:
        raise RuntimeError(
            f"expected MuJoCo {EXPECTED_MUJOCO_VERSION}, got {mujoco.__version__}"
        )

    root = args.wbc_root.resolve()
    model_path = root / MODEL_RELATIVE_PATH
    contract_path = root / CONTRACT_RELATIVE_PATH
    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    joints = contract["joints"]
    if len(joints) != 29 or [joint["index"] for joint in joints] != list(range(29)):
        raise RuntimeError("Mode-5 contract must contain 29 contiguous hardware joints")

    model = mujoco.MjModel.from_xml_path(str(model_path))
    if (model.nq, model.nv, model.nbody, model.njnt) != (36, 35, 31, 30):
        raise RuntimeError(
            "canonical G1 model no longer has free base + 29 hinges + 30 bodies"
        )

    body_names = [
        mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, body_id)
        for body_id in range(1, model.nbody)
    ]
    frames = []
    for root_translation, rpy, policy_joints in zip(
        ROOT_TRANSLATIONS, ROOT_RPY, POLICY_JOINT_FRAMES, strict=True
    ):
        data = mujoco.MjData(model)
        root_quaternion = rpy_to_wxyz(*rpy)
        data.qpos[:3] = root_translation
        data.qpos[3:7] = root_quaternion
        for joint in joints:
            joint_id = mujoco.mj_name2id(
                model, mujoco.mjtObj.mjOBJ_JOINT, joint["name"]
            )
            if joint_id < 1:
                raise RuntimeError(f"contract joint missing from MJCF: {joint['name']}")
            qpos_address = int(model.jnt_qposadr[joint_id])
            policy_index = joint["policy_isaaclab_index"]
            data.qpos[qpos_address] = (
                joint["command_sign"] * policy_joints[policy_index]
                + joint["command_offset_rad"]
            )
        mujoco.mj_forward(model, data)
        frames.append(
            (
                root_translation,
                root_quaternion,
                policy_joints,
                data.xpos[1:].reshape(-1).tolist(),
                data.xquat[1:].reshape(-1).tolist(),
            )
        )

    print("// Generated by generate_fk_mujoco_golden.py; do not hand-edit.")
    print(f"// MuJoCo: {mujoco.__version__}")
    print(f"// Source image: {SOURCE_IMAGE_ID}")
    print(f"// Model SHA-256: {sha256(model_path)}")
    print(f"// Contract SHA-256: {sha256(contract_path)}")
    print("#pragma once")
    print()
    print("#include <array>")
    print("#include <string_view>")
    print()
    print("namespace fk_mujoco_golden {")
    print("struct Frame {")
    print("  std::array<double, 3> root_translation;")
    print("  std::array<double, 4> root_quaternion;")
    print("  std::array<double, 29> policy_joint_positions;")
    print("  std::array<double, 90> body_positions;")
    print("  std::array<double, 120> body_quaternions;")
    print("};")
    print()
    print("inline constexpr std::array<std::string_view, 30> kBodyNames = {")
    for name in body_names:
        print(f'    "{name}",')
    print("};")
    print()
    print("inline constexpr std::array<Frame, 2> kFrames = {{")
    for root_translation, root_quaternion, policy_joints, positions, quaternions in frames:
        print("  Frame{")
        print(f"    std::array<double, 3>{{{cpp_array(root_translation)}}},")
        print(f"    std::array<double, 4>{{{cpp_array(root_quaternion)}}},")
        print(f"    std::array<double, 29>{{{cpp_array(policy_joints)}}},")
        print(f"    std::array<double, 90>{{{cpp_array(positions)}}},")
        print(f"    std::array<double, 120>{{{cpp_array(quaternions)}}},")
        print("  },")
    print("}};")
    print("}  // namespace fk_mujoco_golden")


if __name__ == "__main__":
    main()
